version: '3.8'

volumes:
  db01:

networks:
  net01:
    driver: bridge

services:
  app:
    image: 'selehann_backend'
    volumes:
      - .env/:/app/.env
    ports:
      - '3000:3000'
    restart: always
    environment:
      - .env
    depends_on:
      - database
    networks:
      - net01
    # command: sh -c "apk add --no-cache bash && ./scripts/wait-for-it.sh database:3306 -s"

  database:
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db01:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3307:3306'
    networks:
      - net01
