export enum Texts {
  /////
  LOADING = 'Loading',
  /////
  HOME = 'Home',
  DEVELOPERS = 'Developers',
  NOT_FOUND = 'Not Found',
  /////
  ASK_CONFIRMATION = 'Are you sure?',
  YES = 'Yes',
  NO = 'No',
  ADD = 'Add',
  SAVE = 'Save',
  CONFIRM = 'Confirm',
  CANCEL = 'Cancel',
  EDIT = 'Edit',
  DELETE = 'Delete',
  DELETE_ROW = 'Delete row?',
  DELETE_SELECTED_ROWS = 'Delete selected rows?',
  EXPORT = 'Export',
  EXPORTING = 'Exporting',
  ACTIONS = 'Actions',
  /////
  ID = 'ID',
  AVAILABLE = 'Available',
  ASSIGNED = 'Assigned',
  ACTIVE = 'Active',
  INACTIVE = 'Inactive',
  REGISTRIES = 'Items',
  /////
  USER = 'User',
  FULL_NAME = 'Full name',
  DEVELOPER_NAME = 'Developer',
  DEVELOPER_STATUS = 'Status',
  /////
  SAVE_REGISTRY_SUCCESS = 'Item added!',
  UPDATE_REGISTRY_SUCCESS = 'Item updated!',
  FIELDS_VALIDATION_FAILURE = 'Validation error!',
  FIELD_REQUIRED = 'Field required!',
  ADD_DEVELOPER = 'Add developer',
  DEVELOPER_ADD_OK = 'Developer add successfully!',
  DEVELOPER_ADD_ERROR = 'Error while add developer!',
  /////
  DEVELOPER_STATUS_ERROR = 'Error while updating status!',
  DEVELOPER_RESOURCE_ERROR = 'Error while updating resources!',
  /////
  SERVER_UNAVAILABLE = 'Server unavailable!',
  LOGIN_SUCCESS = 'Logged in successfully!',
  LOGIN_FAILED = 'Invalid credentials!',
  PASSWORDS_DOES_NOT_MATCH = "Passwords doesn't match!",
  USER_ALREADY_EXIST = 'User already exist!',
  REGISTER_FAILED = 'Error while register!',
  SESSION_EXPIRED = 'Session has expired!',
  SESSION_ENDED = 'Session has ended!',
}
